language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - cmake
            - cmake-data
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

compiler: gcc

jobs:
  include:
    - stage: build
      name: "Build"
      script: ./build.sh

stages:
  - build
